Update configure and ChangeLog.
(Old svn revision: 7995)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24295,23 +24295,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for libxfce4util-1.0 >= 4.1.91" >&5
-echo $ECHO_N "checking for libxfce4util-1.0 >= 4.1.91... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for libxfce4util-1.0 >= 4.1.99" >&5
+echo $ECHO_N "checking for libxfce4util-1.0 >= 4.1.99... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "libxfce4util-1.0 >= 4.1.91" ; then
+        if $PKG_CONFIG --exists "libxfce4util-1.0 >= 4.1.99" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking LIBXFCE4UTIL_CFLAGS" >&5
 echo $ECHO_N "checking LIBXFCE4UTIL_CFLAGS... $ECHO_C" >&6
-            LIBXFCE4UTIL_CFLAGS=`$PKG_CONFIG --cflags "libxfce4util-1.0 >= 4.1.91"`
+            LIBXFCE4UTIL_CFLAGS=`$PKG_CONFIG --cflags "libxfce4util-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $LIBXFCE4UTIL_CFLAGS" >&5
 echo "${ECHO_T}$LIBXFCE4UTIL_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking LIBXFCE4UTIL_LIBS" >&5
 echo $ECHO_N "checking LIBXFCE4UTIL_LIBS... $ECHO_C" >&6
-            LIBXFCE4UTIL_LIBS=`$PKG_CONFIG --libs "libxfce4util-1.0 >= 4.1.91"`
+            LIBXFCE4UTIL_LIBS=`$PKG_CONFIG --libs "libxfce4util-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $LIBXFCE4UTIL_LIBS" >&5
 echo "${ECHO_T}$LIBXFCE4UTIL_LIBS" >&6
         else
@@ -24319,7 +24319,7 @@ echo "${ECHO_T}$LIBXFCE4UTIL_LIBS" >&6
             LIBXFCE4UTIL_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            LIBXFCE4UTIL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfce4util-1.0 >= 4.1.91"`
+            LIBXFCE4UTIL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfce4util-1.0 >= 4.1.99"`
             echo $LIBXFCE4UTIL_PKG_ERRORS
         fi
 
@@ -24334,12 +24334,12 @@ echo "${ECHO_T}$LIBXFCE4UTIL_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (libxfce4util-1.0 >= 4.1.91) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (libxfce4util-1.0 >= 4.1.91) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (libxfce4util-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libxfce4util-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
-  LIBXFCE4UTIL_REQUIRED_VERSION=4.1.91
+  LIBXFCE4UTIL_REQUIRED_VERSION=4.1.99
 
 
 
@@ -24397,23 +24397,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for libxfcegui4-1.0 >= 4.1.91" >&5
-echo $ECHO_N "checking for libxfcegui4-1.0 >= 4.1.91... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for libxfcegui4-1.0 >= 4.1.99" >&5
+echo $ECHO_N "checking for libxfcegui4-1.0 >= 4.1.99... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "libxfcegui4-1.0 >= 4.1.91" ; then
+        if $PKG_CONFIG --exists "libxfcegui4-1.0 >= 4.1.99" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking LIBXFCEGUI4_CFLAGS" >&5
 echo $ECHO_N "checking LIBXFCEGUI4_CFLAGS... $ECHO_C" >&6
-            LIBXFCEGUI4_CFLAGS=`$PKG_CONFIG --cflags "libxfcegui4-1.0 >= 4.1.91"`
+            LIBXFCEGUI4_CFLAGS=`$PKG_CONFIG --cflags "libxfcegui4-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $LIBXFCEGUI4_CFLAGS" >&5
 echo "${ECHO_T}$LIBXFCEGUI4_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking LIBXFCEGUI4_LIBS" >&5
 echo $ECHO_N "checking LIBXFCEGUI4_LIBS... $ECHO_C" >&6
-            LIBXFCEGUI4_LIBS=`$PKG_CONFIG --libs "libxfcegui4-1.0 >= 4.1.91"`
+            LIBXFCEGUI4_LIBS=`$PKG_CONFIG --libs "libxfcegui4-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $LIBXFCEGUI4_LIBS" >&5
 echo "${ECHO_T}$LIBXFCEGUI4_LIBS" >&6
         else
@@ -24421,7 +24421,7 @@ echo "${ECHO_T}$LIBXFCEGUI4_LIBS" >&6
             LIBXFCEGUI4_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            LIBXFCEGUI4_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfcegui4-1.0 >= 4.1.91"`
+            LIBXFCEGUI4_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfcegui4-1.0 >= 4.1.99"`
             echo $LIBXFCEGUI4_PKG_ERRORS
         fi
 
@@ -24436,12 +24436,12 @@ echo "${ECHO_T}$LIBXFCEGUI4_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (libxfcegui4-1.0 >= 4.1.91) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (libxfcegui4-1.0 >= 4.1.91) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (libxfcegui4-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libxfcegui4-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
-  LIBXFCEGUI4_REQUIRED_VERSION=4.1.91
+  LIBXFCEGUI4_REQUIRED_VERSION=4.1.99
 
 
 
@@ -24499,23 +24499,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for libxfce4mcs-client-1.0 >= 4.1.91" >&5
-echo $ECHO_N "checking for libxfce4mcs-client-1.0 >= 4.1.91... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for libxfce4mcs-client-1.0 >= 4.1.99" >&5
+echo $ECHO_N "checking for libxfce4mcs-client-1.0 >= 4.1.99... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "libxfce4mcs-client-1.0 >= 4.1.91" ; then
+        if $PKG_CONFIG --exists "libxfce4mcs-client-1.0 >= 4.1.99" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking LIBXFCE4MCS_CLIENT_CFLAGS" >&5
 echo $ECHO_N "checking LIBXFCE4MCS_CLIENT_CFLAGS... $ECHO_C" >&6
-            LIBXFCE4MCS_CLIENT_CFLAGS=`$PKG_CONFIG --cflags "libxfce4mcs-client-1.0 >= 4.1.91"`
+            LIBXFCE4MCS_CLIENT_CFLAGS=`$PKG_CONFIG --cflags "libxfce4mcs-client-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $LIBXFCE4MCS_CLIENT_CFLAGS" >&5
 echo "${ECHO_T}$LIBXFCE4MCS_CLIENT_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking LIBXFCE4MCS_CLIENT_LIBS" >&5
 echo $ECHO_N "checking LIBXFCE4MCS_CLIENT_LIBS... $ECHO_C" >&6
-            LIBXFCE4MCS_CLIENT_LIBS=`$PKG_CONFIG --libs "libxfce4mcs-client-1.0 >= 4.1.91"`
+            LIBXFCE4MCS_CLIENT_LIBS=`$PKG_CONFIG --libs "libxfce4mcs-client-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $LIBXFCE4MCS_CLIENT_LIBS" >&5
 echo "${ECHO_T}$LIBXFCE4MCS_CLIENT_LIBS" >&6
         else
@@ -24523,7 +24523,7 @@ echo "${ECHO_T}$LIBXFCE4MCS_CLIENT_LIBS" >&6
             LIBXFCE4MCS_CLIENT_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            LIBXFCE4MCS_CLIENT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfce4mcs-client-1.0 >= 4.1.91"`
+            LIBXFCE4MCS_CLIENT_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libxfce4mcs-client-1.0 >= 4.1.99"`
             echo $LIBXFCE4MCS_CLIENT_PKG_ERRORS
         fi
 
@@ -24538,12 +24538,12 @@ echo "${ECHO_T}$LIBXFCE4MCS_CLIENT_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (libxfce4mcs-client-1.0 >= 4.1.91) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (libxfce4mcs-client-1.0 >= 4.1.91) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (libxfce4mcs-client-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (libxfce4mcs-client-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
-  LIBXFCE4MCS_CLIENT_REQUIRED_VERSION=4.1.91
+  LIBXFCE4MCS_CLIENT_REQUIRED_VERSION=4.1.99
 
 
 
@@ -24602,23 +24602,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for xfce4-panel-1.0 >= 4.1.91" >&5
-echo $ECHO_N "checking for xfce4-panel-1.0 >= 4.1.91... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for xfce4-panel-1.0 >= 4.1.99" >&5
+echo $ECHO_N "checking for xfce4-panel-1.0 >= 4.1.99... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "xfce4-panel-1.0 >= 4.1.91" ; then
+        if $PKG_CONFIG --exists "xfce4-panel-1.0 >= 4.1.99" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking XFCE4_PANEL_CFLAGS" >&5
 echo $ECHO_N "checking XFCE4_PANEL_CFLAGS... $ECHO_C" >&6
-            XFCE4_PANEL_CFLAGS=`$PKG_CONFIG --cflags "xfce4-panel-1.0 >= 4.1.91"`
+            XFCE4_PANEL_CFLAGS=`$PKG_CONFIG --cflags "xfce4-panel-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE4_PANEL_CFLAGS" >&5
 echo "${ECHO_T}$XFCE4_PANEL_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking XFCE4_PANEL_LIBS" >&5
 echo $ECHO_N "checking XFCE4_PANEL_LIBS... $ECHO_C" >&6
-            XFCE4_PANEL_LIBS=`$PKG_CONFIG --libs "xfce4-panel-1.0 >= 4.1.91"`
+            XFCE4_PANEL_LIBS=`$PKG_CONFIG --libs "xfce4-panel-1.0 >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE4_PANEL_LIBS" >&5
 echo "${ECHO_T}$XFCE4_PANEL_LIBS" >&6
         else
@@ -24626,7 +24626,7 @@ echo "${ECHO_T}$XFCE4_PANEL_LIBS" >&6
             XFCE4_PANEL_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            XFCE4_PANEL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xfce4-panel-1.0 >= 4.1.91"`
+            XFCE4_PANEL_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xfce4-panel-1.0 >= 4.1.99"`
             echo $XFCE4_PANEL_PKG_ERRORS
         fi
 
@@ -24641,12 +24641,12 @@ echo "${ECHO_T}$XFCE4_PANEL_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (xfce4-panel-1.0 >= 4.1.91) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (xfce4-panel-1.0 >= 4.1.91) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (xfce4-panel-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (xfce4-panel-1.0 >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
-  XFCE4_PANEL_REQUIRED_VERSION=4.1.91
+  XFCE4_PANEL_REQUIRED_VERSION=4.1.99
 
 
 
@@ -24734,23 +24734,23 @@ fi
   else
      PKG_CONFIG_MIN_VERSION=0.9.0
      if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
-        echo "$as_me:$LINENO: checking for xfce-mcs-manager >= 4.1.91" >&5
-echo $ECHO_N "checking for xfce-mcs-manager >= 4.1.91... $ECHO_C" >&6
+        echo "$as_me:$LINENO: checking for xfce-mcs-manager >= 4.1.99" >&5
+echo $ECHO_N "checking for xfce-mcs-manager >= 4.1.99... $ECHO_C" >&6
 
-        if $PKG_CONFIG --exists "xfce-mcs-manager >= 4.1.91" ; then
+        if $PKG_CONFIG --exists "xfce-mcs-manager >= 4.1.99" ; then
             echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
             succeeded=yes
 
             echo "$as_me:$LINENO: checking XFCE_MCS_MANAGER_CFLAGS" >&5
 echo $ECHO_N "checking XFCE_MCS_MANAGER_CFLAGS... $ECHO_C" >&6
-            XFCE_MCS_MANAGER_CFLAGS=`$PKG_CONFIG --cflags "xfce-mcs-manager >= 4.1.91"`
+            XFCE_MCS_MANAGER_CFLAGS=`$PKG_CONFIG --cflags "xfce-mcs-manager >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE_MCS_MANAGER_CFLAGS" >&5
 echo "${ECHO_T}$XFCE_MCS_MANAGER_CFLAGS" >&6
 
             echo "$as_me:$LINENO: checking XFCE_MCS_MANAGER_LIBS" >&5
 echo $ECHO_N "checking XFCE_MCS_MANAGER_LIBS... $ECHO_C" >&6
-            XFCE_MCS_MANAGER_LIBS=`$PKG_CONFIG --libs "xfce-mcs-manager >= 4.1.91"`
+            XFCE_MCS_MANAGER_LIBS=`$PKG_CONFIG --libs "xfce-mcs-manager >= 4.1.99"`
             echo "$as_me:$LINENO: result: $XFCE_MCS_MANAGER_LIBS" >&5
 echo "${ECHO_T}$XFCE_MCS_MANAGER_LIBS" >&6
         else
@@ -24758,7 +24758,7 @@ echo "${ECHO_T}$XFCE_MCS_MANAGER_LIBS" >&6
             XFCE_MCS_MANAGER_LIBS=""
             ## If we have a custom action on failure, don't print errors, but
             ## do set a variable so people can do so.
-            XFCE_MCS_MANAGER_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xfce-mcs-manager >= 4.1.91"`
+            XFCE_MCS_MANAGER_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xfce-mcs-manager >= 4.1.99"`
             echo $XFCE_MCS_MANAGER_PKG_ERRORS
         fi
 
@@ -24773,12 +24773,12 @@ echo "${ECHO_T}$XFCE_MCS_MANAGER_LIBS" >&6
   if test $succeeded = yes; then
      :
   else
-     { { echo "$as_me:$LINENO: error: Library requirements (xfce-mcs-manager >= 4.1.91) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
-echo "$as_me: error: Library requirements (xfce-mcs-manager >= 4.1.91) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+     { { echo "$as_me:$LINENO: error: Library requirements (xfce-mcs-manager >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (xfce-mcs-manager >= 4.1.99) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
 
-  XFCE_MCS_MANAGER_REQUIRED_VERSION=4.1.91
+  XFCE_MCS_MANAGER_REQUIRED_VERSION=4.1.99
 
 
 
