autotools update.
(Old svn revision: 7228)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -271,7 +271,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="common/backdrop.c"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S RANLIB ac_ct_RANLIB LIBTOOL CPP EGREP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS LIBX11_CFLAGS LIBX11_LDFLAGS LIBX11_LIBS PKG_CONFIG GLIB_CFLAGS GLIB_LIBS GTK_CFLAGS GTK_LIBS LIBXFCEGUI4_CFLAGS LIBXFCEGUI4_LIBS LIBXFCE4UTIL_CFLAGS LIBXFCE4UTIL_LIBS LIBXML_CFLAGS LIBXML_LIBS LIBXFCE4MCS_CLIENT_CFLAGS LIBXFCE4MCS_CLIENT_LIBS LIBXFCE4MCS_MANAGER_CFLAGS LIBXFCE4MCS_MANAGER_LIBS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S RANLIB ac_ct_RANLIB LIBTOOL CPP EGREP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS LIBX11_CFLAGS LIBX11_LDFLAGS LIBX11_LIBS PKG_CONFIG GLIB_CFLAGS GLIB_LIBS GLIB_REQUIRED_VERSION PANGO_CFLAGS PANGO_LIBS PANGO_REQUIRED_VERSION GTK_CFLAGS GTK_LIBS GTK_REQUIRED_VERSION LIBXFCEGUI4_CFLAGS LIBXFCEGUI4_LIBS LIBXFCEGUI4_REQUIRED_VERSION LIBXFCE4UTIL_CFLAGS LIBXFCE4UTIL_LIBS LIBXFCE4UTIL_REQUIRED_VERSION LIBXML_CFLAGS LIBXML_LIBS LIBXML_REQUIRED_VERSION LIBXFCE4MCS_CLIENT_CFLAGS LIBXFCE4MCS_CLIENT_LIBS LIBXFCE4MCS_CLIENT_REQUIRED_VERSION LIBXFCE4MCS_MANAGER_CFLAGS LIBXFCE4MCS_MANAGER_LIBS LIBXFCE4MCS_MANAGER_REQUIRED_VERSION LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -5562,6 +5562,7 @@ echo "$as_me: error: X Window system libraries and header files are required" >&
 
 
 
+
   succeeded=no
 
   if test -z "$PKG_CONFIG"; then
@@ -5658,6 +5659,112 @@ echo "${ECHO_T}$GLIB_LIBS" >&6
 echo "$as_me: error: Library requirements (glib-2.0 >= 2.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
+
+  GLIB_REQUIRED_VERSION=2.0.0
+
+
+
+
+  succeeded=no
+
+  if test -z "$PKG_CONFIG"; then
+    # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+
+if test -n "$PKG_CONFIG"; then
+  echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  fi
+
+  if test "$PKG_CONFIG" = "no" ; then
+     echo "*** The pkg-config script could not be found. Make sure it is"
+     echo "*** in your path, or set the PKG_CONFIG environment variable"
+     echo "*** to the full path to pkg-config."
+     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+  else
+     PKG_CONFIG_MIN_VERSION=0.9.0
+     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
+        echo "$as_me:$LINENO: checking for pango >= 1.0.0" >&5
+echo $ECHO_N "checking for pango >= 1.0.0... $ECHO_C" >&6
+
+        if $PKG_CONFIG --exists "pango >= 1.0.0" ; then
+            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+            succeeded=yes
+
+            echo "$as_me:$LINENO: checking PANGO_CFLAGS" >&5
+echo $ECHO_N "checking PANGO_CFLAGS... $ECHO_C" >&6
+            PANGO_CFLAGS=`$PKG_CONFIG --cflags "pango >= 1.0.0"`
+            echo "$as_me:$LINENO: result: $PANGO_CFLAGS" >&5
+echo "${ECHO_T}$PANGO_CFLAGS" >&6
+
+            echo "$as_me:$LINENO: checking PANGO_LIBS" >&5
+echo $ECHO_N "checking PANGO_LIBS... $ECHO_C" >&6
+            PANGO_LIBS=`$PKG_CONFIG --libs "pango >= 1.0.0"`
+            echo "$as_me:$LINENO: result: $PANGO_LIBS" >&5
+echo "${ECHO_T}$PANGO_LIBS" >&6
+        else
+            PANGO_CFLAGS=""
+            PANGO_LIBS=""
+            ## If we have a custom action on failure, don't print errors, but
+            ## do set a variable so people can do so.
+            PANGO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "pango >= 1.0.0"`
+            echo $PANGO_PKG_ERRORS
+        fi
+
+
+
+     else
+        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
+        echo "*** See http://www.freedesktop.org/software/pkgconfig"
+     fi
+  fi
+
+  if test $succeeded = yes; then
+     :
+  else
+     { { echo "$as_me:$LINENO: error: Library requirements (pango >= 1.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (pango >= 1.0.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+  PANGO_REQUIRED_VERSION=1.0.0
+
+
 
 
   succeeded=no
@@ -5757,6 +5864,10 @@ echo "$as_me: error: Library requirements (gtk+-2.0 >= 2.0.0) not met; consider 
    { (exit 1); exit 1; }; }
   fi
 
+  GTK_REQUIRED_VERSION=2.0.0
+
+
+
 
   succeeded=no
 
@@ -5854,6 +5965,10 @@ echo "${ECHO_T}$LIBXFCEGUI4_LIBS" >&6
 echo "$as_me: error: Library requirements (libxfcegui4-1.0 >= 0.0.17) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
+
+  LIBXFCEGUI4_REQUIRED_VERSION=0.0.17
+
+
 
 
   succeeded=no
@@ -5953,6 +6068,10 @@ echo "$as_me: error: Library requirements (libxfce4util-1.0 >= 0.0) not met; con
    { (exit 1); exit 1; }; }
   fi
 
+  LIBXFCE4UTIL_REQUIRED_VERSION=0.0
+
+
+
 
   succeeded=no
 
@@ -6050,6 +6169,10 @@ echo "${ECHO_T}$LIBXML_LIBS" >&6
 echo "$as_me: error: Library requirements (libxml-2.0 >= 2.4.0) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
+
+  LIBXML_REQUIRED_VERSION=2.4.0
+
+
 
 
   succeeded=no
@@ -6149,6 +6272,10 @@ echo "$as_me: error: Library requirements (libxfce4mcs-client-1.0 >= 0.0.4) not 
    { (exit 1); exit 1; }; }
   fi
 
+  LIBXFCE4MCS_CLIENT_REQUIRED_VERSION=0.0.4
+
+
+
 
   succeeded=no
 
@@ -6246,6 +6373,9 @@ echo "${ECHO_T}$LIBXFCE4MCS_MANAGER_LIBS" >&6
 echo "$as_me: error: Library requirements (libxfce4mcs-manager-1.0 >= 0.0.4) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
    { (exit 1); exit 1; }; }
   fi
+
+  LIBXFCE4MCS_MANAGER_REQUIRED_VERSION=0.0.4
+
 
 
 
@@ -6993,18 +7123,28 @@ s,@LIBX11_LIBS@,$LIBX11_LIBS,;t t
 s,@PKG_CONFIG@,$PKG_CONFIG,;t t
 s,@GLIB_CFLAGS@,$GLIB_CFLAGS,;t t
 s,@GLIB_LIBS@,$GLIB_LIBS,;t t
+s,@GLIB_REQUIRED_VERSION@,$GLIB_REQUIRED_VERSION,;t t
+s,@PANGO_CFLAGS@,$PANGO_CFLAGS,;t t
+s,@PANGO_LIBS@,$PANGO_LIBS,;t t
+s,@PANGO_REQUIRED_VERSION@,$PANGO_REQUIRED_VERSION,;t t
 s,@GTK_CFLAGS@,$GTK_CFLAGS,;t t
 s,@GTK_LIBS@,$GTK_LIBS,;t t
+s,@GTK_REQUIRED_VERSION@,$GTK_REQUIRED_VERSION,;t t
 s,@LIBXFCEGUI4_CFLAGS@,$LIBXFCEGUI4_CFLAGS,;t t
 s,@LIBXFCEGUI4_LIBS@,$LIBXFCEGUI4_LIBS,;t t
+s,@LIBXFCEGUI4_REQUIRED_VERSION@,$LIBXFCEGUI4_REQUIRED_VERSION,;t t
 s,@LIBXFCE4UTIL_CFLAGS@,$LIBXFCE4UTIL_CFLAGS,;t t
 s,@LIBXFCE4UTIL_LIBS@,$LIBXFCE4UTIL_LIBS,;t t
+s,@LIBXFCE4UTIL_REQUIRED_VERSION@,$LIBXFCE4UTIL_REQUIRED_VERSION,;t t
 s,@LIBXML_CFLAGS@,$LIBXML_CFLAGS,;t t
 s,@LIBXML_LIBS@,$LIBXML_LIBS,;t t
+s,@LIBXML_REQUIRED_VERSION@,$LIBXML_REQUIRED_VERSION,;t t
 s,@LIBXFCE4MCS_CLIENT_CFLAGS@,$LIBXFCE4MCS_CLIENT_CFLAGS,;t t
 s,@LIBXFCE4MCS_CLIENT_LIBS@,$LIBXFCE4MCS_CLIENT_LIBS,;t t
+s,@LIBXFCE4MCS_CLIENT_REQUIRED_VERSION@,$LIBXFCE4MCS_CLIENT_REQUIRED_VERSION,;t t
 s,@LIBXFCE4MCS_MANAGER_CFLAGS@,$LIBXFCE4MCS_MANAGER_CFLAGS,;t t
 s,@LIBXFCE4MCS_MANAGER_LIBS@,$LIBXFCE4MCS_MANAGER_LIBS,;t t
+s,@LIBXFCE4MCS_MANAGER_REQUIRED_VERSION@,$LIBXFCE4MCS_MANAGER_REQUIRED_VERSION,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
