#ifdef out all the menu loading code in xfdesktop (including the stub loader) if --disable-desktop-menu is specified
(Old svn revision: 7636)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL GETTEXT_PACKAGE USE_NLS MSGFMT GMSGFMT XGETTEXT CATALOGS CATOBJEXT DATADIRNAME GMOFILES INSTOBJEXT INTLLIBS PO_IN_DATADIR_TRUE PO_IN_DATADIR_FALSE POFILES POSUB MKINSTALLDIRS localedir X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS LIBX11_CFLAGS LIBX11_LDFLAGS LIBX11_LIBS PKG_CONFIG XFCE4_PANEL_CFLAGS XFCE4_PANEL_LIBS XFCE4_PANEL_REQUIRED_VERSION XFCE4_PANEL_PLUGINSDIR LIBXFCEGUI4_CFLAGS LIBXFCEGUI4_LIBS LIBXFCEGUI4_REQUIRED_VERSION LIBXFCE4UTIL_CFLAGS LIBXFCE4UTIL_LIBS LIBXFCE4UTIL_REQUIRED_VERSION LIBXFCE4MCS_CLIENT_CFLAGS LIBXFCE4MCS_CLIENT_LIBS LIBXFCE4MCS_CLIENT_REQUIRED_VERSION GMODULE_CFLAGS GMODULE_LIBS GMODULE_REQUIRED_VERSION GTHREAD_CFLAGS GTHREAD_LIBS GTHREAD_REQUIRED_VERSION LIBXML_CFLAGS LIBXML_LIBS LIBXML_REQUIRED_VERSION MENUEDITOR_DIR XFCE_MCS_MANAGER_CFLAGS XFCE_MCS_MANAGER_LIBS XFCE_MCS_MANAGER_REQUIRED_VERSION XFCE_MCS_MANAGER_PLUGINSDIR DESKTOP_MENU_DIR PANEL_PLUGIN_DIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL GETTEXT_PACKAGE USE_NLS MSGFMT GMSGFMT XGETTEXT CATALOGS CATOBJEXT DATADIRNAME GMOFILES INSTOBJEXT INTLLIBS PO_IN_DATADIR_TRUE PO_IN_DATADIR_FALSE POFILES POSUB MKINSTALLDIRS localedir X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS LIBX11_CFLAGS LIBX11_LDFLAGS LIBX11_LIBS PKG_CONFIG XFCE4_PANEL_CFLAGS XFCE4_PANEL_LIBS XFCE4_PANEL_REQUIRED_VERSION XFCE4_PANEL_PLUGINSDIR LIBXFCEGUI4_CFLAGS LIBXFCEGUI4_LIBS LIBXFCEGUI4_REQUIRED_VERSION LIBXFCE4UTIL_CFLAGS LIBXFCE4UTIL_LIBS LIBXFCE4UTIL_REQUIRED_VERSION LIBXFCE4MCS_CLIENT_CFLAGS LIBXFCE4MCS_CLIENT_LIBS LIBXFCE4MCS_CLIENT_REQUIRED_VERSION GMODULE_CFLAGS GMODULE_LIBS GMODULE_REQUIRED_VERSION GTHREAD_CFLAGS GTHREAD_LIBS GTHREAD_REQUIRED_VERSION LIBXML_CFLAGS LIBXML_LIBS LIBXML_REQUIRED_VERSION MENUEDITOR_DIR XFCE_MCS_MANAGER_CFLAGS XFCE_MCS_MANAGER_LIBS XFCE_MCS_MANAGER_REQUIRED_VERSION XFCE_MCS_MANAGER_PLUGINSDIR DESKTOP_MENU_DIR BUILD_DESKTOP_MENU_STUB_TRUE BUILD_DESKTOP_MENU_STUB_FALSE PANEL_PLUGIN_DIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1041,6 +1041,9 @@ Optional Features:
   --enable-libxml2        Enable checking for libxml2 (for xfce4-menueditor)
                           (default=yes)
   --disable-libxml2       Disable checking for libxml2 (for xfce4-menueditor)
+  --disable-desktop-menu  Do not build the desktop menu module
+                          (default=enabled)
+  --disable-panel-plugin  Do not build the panel plugin (default=enabled)
   --enable-debug=yes|no|full
                           Build with debugging support
   --disable-debug         Include no debugging support default
@@ -1052,9 +1055,6 @@ Optional Features:
                           (default)
   --enable-asserts        Enable assert statements (default)
   --disable-asserts       Disable assert statements (USE WITH CARE!!!)
-  --disable-desktop-menu  Do not build the desktop menu module
-                          (default=enabled)
-  --disable-panel-plugin  Do not build the panel plugin (default=enabled)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -24831,6 +24831,54 @@ echo "${ECHO_T}$XFCE_MCS_MANAGER_PLUGINSDIR" >&6
 
 
 
+# Check whether --enable-desktop-menu or --disable-desktop-menu was given.
+if test "${enable_desktop_menu+set}" = set; then
+  enableval="$enable_desktop_menu"
+  ac_cv_enable_desktop_menu=$enableval
+else
+  ac_cv_enable_desktop_menu=yes
+fi;
+if test "x$ac_cv_enable_desktop_menu" = "xno"; then
+	DESKTOP_MENU_DIR=""
+	build_desktop_menu="no"
+else
+	DESKTOP_MENU_DIR="menu"
+	build_desktop_menu="yes"
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_DESKTOP_MENU 1
+_ACEOF
+
+fi
+
+
+
+if test "x$build_desktop_menu" = "xyes" ; then
+  BUILD_DESKTOP_MENU_STUB_TRUE=
+  BUILD_DESKTOP_MENU_STUB_FALSE='#'
+else
+  BUILD_DESKTOP_MENU_STUB_TRUE='#'
+  BUILD_DESKTOP_MENU_STUB_FALSE=
+fi
+
+
+# Check whether --enable-panel-plugin or --disable-panel-plugin was given.
+if test "${enable_panel_plugin+set}" = set; then
+  enableval="$enable_panel_plugin"
+  ac_cv_enable_panel_plugin=$enableval
+else
+  ac_cv_enable_panel_plugin=yes
+fi;
+if test "x$ac_cv_enable_panel_plugin" = "xno" -o "x$build_desktop_menu" = "xno"; then
+	PANEL_PLUGIN_DIR=""
+	build_panel_plugin="no"
+else
+	PANEL_PLUGIN_DIR="panel-plugin"
+	build_panel_plugin="yes"
+fi
+
+
+
   # Check whether --enable-debug or --disable-debug was given.
 if test "${enable_debug+set}" = set; then
   enableval="$enable_debug"
@@ -24922,39 +24970,6 @@ echo "${ECHO_T}no" >&6
     echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
   fi
-
-
-
-# Check whether --enable-desktop-menu or --disable-desktop-menu was given.
-if test "${enable_desktop_menu+set}" = set; then
-  enableval="$enable_desktop_menu"
-  ac_cv_enable_desktop_menu=$enableval
-else
-  ac_cv_enable_desktop_menu=yes
-fi;
-if test "x$ac_cv_enable_desktop_menu" = "xno"; then
-	DESKTOP_MENU_DIR=""
-	build_desktop_menu="no"
-else
-	DESKTOP_MENU_DIR="menu"
-	build_desktop_menu="yes"
-fi
-
-
-# Check whether --enable-panel-plugin or --disable-panel-plugin was given.
-if test "${enable_panel_plugin+set}" = set; then
-  enableval="$enable_panel_plugin"
-  ac_cv_enable_panel_plugin=$enableval
-else
-  ac_cv_enable_panel_plugin=yes
-fi;
-if test "x$ac_cv_enable_panel_plugin" = "xno" -o "x$build_desktop_menu" = "xno"; then
-	PANEL_PLUGIN_DIR=""
-	build_panel_plugin="no"
-else
-	PANEL_PLUGIN_DIR="panel-plugin"
-	build_panel_plugin="yes"
-fi
 
 
                                                                                                                                                                           ac_config_files="$ac_config_files backdrops/Makefile common/Makefile doc/Makefile doc/C/Makefile doc/C/images/Makefile doc/fr/Makefile doc/fr/images/Makefile Makefile menueditor/Makefile modules/Makefile modules/menu/Makefile panel-plugin/Makefile pixmaps/Makefile po/Makefile.in settings/Makefile src/Makefile xfdesktop.spec"
@@ -25081,6 +25096,13 @@ if test -z "${am__fastdepCXX_TRUE}" && test -z "${am__fastdepCXX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_DESKTOP_MENU_STUB_TRUE}" && test -z "${BUILD_DESKTOP_MENU_STUB_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_DESKTOP_MENU_STUB\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_DESKTOP_MENU_STUB\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -25753,6 +25775,8 @@ s,@XFCE_MCS_MANAGER_LIBS@,$XFCE_MCS_MANAGER_LIBS,;t t
 s,@XFCE_MCS_MANAGER_REQUIRED_VERSION@,$XFCE_MCS_MANAGER_REQUIRED_VERSION,;t t
 s,@XFCE_MCS_MANAGER_PLUGINSDIR@,$XFCE_MCS_MANAGER_PLUGINSDIR,;t t
 s,@DESKTOP_MENU_DIR@,$DESKTOP_MENU_DIR,;t t
+s,@BUILD_DESKTOP_MENU_STUB_TRUE@,$BUILD_DESKTOP_MENU_STUB_TRUE,;t t
+s,@BUILD_DESKTOP_MENU_STUB_FALSE@,$BUILD_DESKTOP_MENU_STUB_FALSE,;t t
 s,@PANEL_PLUGIN_DIR@,$PANEL_PLUGIN_DIR,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
